import { EnvType } from './env.types';

export const AWS_S3_FIELDS = ['AWS_S3_BUCKET_NAME', 'AWS_ACCESS_KEY_ID', 'AWS_SECRET_ACCESS_KEY', 'AWS_DEFAULT_REGION'];

// defaults
const TESTING_COOKIE_SECRET = 'cookie-secret';
const TESTING_ACCESS_TOKEN_SECRET = 'access-token-secret';
const TESTING_ACCESS_TOKEN_EXPIRES_IN_SECONDS = 180; // 3 min
const TESTING_REFRESH_TOKEN_SECRET = 'refresh-token-secret';
const TESTING_REFRESH_TOKEN_EXPIRES_IN_SECONDS = 600; // 10 min

const COMMON_MONGO_PARAMS = '';
const COMMON_MONGO_MAX_POOL_SIZE = 25;
const COMMON_MONGO_SERVER_SELECTION_TIMEOUT_MS = 5000;
const COMMON_MONGO_CONNECT_TIMEOUT_MS = 5000;

export const DEFAULT_DEVELOPMENT_ENV: Partial<EnvType> = {
	// API
	API_ENV: 'development',
	API_HOST: '0.0.0.0',
	API_PORT: 3333,
	// Logger
	LOG_ENABLED: true,
	LOG_LEVEL: 'debug',
	// MongoDB
	MONGO_PROTOCOL: 'mongodb',
	MONGO_HOST: 'localhost',
	MONGO_PORT: 27017,
	MONGO_PARAMS: COMMON_MONGO_PARAMS,
	MONGO_MAX_POOL_SIZE: COMMON_MONGO_MAX_POOL_SIZE,
	MONGO_SERVER_SELECTION_TIMEOUT_MS: COMMON_MONGO_SERVER_SELECTION_TIMEOUT_MS,
	MONGO_CONNECT_TIMEOUT_MS: COMMON_MONGO_CONNECT_TIMEOUT_MS,
	// Storage type
	STORAGE_TYPE: 'local',
};

export const DEFAULT_PRODUCTION_ENV: Partial<EnvType> = {
	// API
	API_ENV: 'production',
	API_HOST: '0.0.0.0',
	API_PORT: 3333,
	// Logger
	LOG_ENABLED: true,
	LOG_LEVEL: 'info',
	// MongoDB
	MONGO_PARAMS: COMMON_MONGO_PARAMS,
	MONGO_MAX_POOL_SIZE: COMMON_MONGO_MAX_POOL_SIZE,
	MONGO_SERVER_SELECTION_TIMEOUT_MS: COMMON_MONGO_SERVER_SELECTION_TIMEOUT_MS,
	MONGO_CONNECT_TIMEOUT_MS: COMMON_MONGO_CONNECT_TIMEOUT_MS,
};

export const DEFAULT_TESTING_ENV: Partial<EnvType> = {
	// API
	API_ENV: 'development',
	API_HOST: '0.0.0.0',
	API_PORT: 3333,
	// Logger
	LOG_ENABLED: false,
	LOG_LEVEL: 'info',
	// Auth
	COOKIE_SECRET: TESTING_COOKIE_SECRET,
	ACCESS_TOKEN_SECRET: TESTING_ACCESS_TOKEN_SECRET,
	ACCESS_TOKEN_EXPIRES_IN_SECONDS: TESTING_ACCESS_TOKEN_EXPIRES_IN_SECONDS,
	REFRESH_TOKEN_SECRET: TESTING_REFRESH_TOKEN_SECRET,
	REFRESH_TOKEN_EXPIRES_IN_SECONDS: TESTING_REFRESH_TOKEN_EXPIRES_IN_SECONDS,
	// MongoDB
	MONGO_PROTOCOL: '',
	MONGO_USERNAME: '',
	MONGO_PASSWORD: '',
	MONGO_DATABASE: '',
	MONGO_HOST: '',
	MONGO_PORT: 0,
	MONGO_PARAMS: '',
	MONGO_MAX_POOL_SIZE: 0,
	MONGO_SERVER_SELECTION_TIMEOUT_MS: 0,
	MONGO_CONNECT_TIMEOUT_MS: 0,
	// Storage type
	STORAGE_TYPE: 'local',
};

export const DEFAULT_E2E_ENV: Partial<EnvType> = {
	// API
	API_ENV: 'development',
	API_HOST: '0.0.0.0',
	API_PORT: 3333,
	// Logger
	LOG_ENABLED: false,
	LOG_LEVEL: 'info',
	// Auth
	COOKIE_SECRET: TESTING_COOKIE_SECRET,
	ACCESS_TOKEN_SECRET: TESTING_ACCESS_TOKEN_SECRET,
	ACCESS_TOKEN_EXPIRES_IN_SECONDS: TESTING_ACCESS_TOKEN_EXPIRES_IN_SECONDS,
	REFRESH_TOKEN_SECRET: TESTING_REFRESH_TOKEN_SECRET,
	REFRESH_TOKEN_EXPIRES_IN_SECONDS: TESTING_REFRESH_TOKEN_EXPIRES_IN_SECONDS,
	// MongoDB
	MONGO_PROTOCOL: 'mongodb',
	MONGO_HOST: 'localhost',
	MONGO_PORT: 27017,
	MONGO_PARAMS: COMMON_MONGO_PARAMS,
	MONGO_MAX_POOL_SIZE: COMMON_MONGO_MAX_POOL_SIZE,
	MONGO_SERVER_SELECTION_TIMEOUT_MS: COMMON_MONGO_SERVER_SELECTION_TIMEOUT_MS,
	MONGO_CONNECT_TIMEOUT_MS: COMMON_MONGO_CONNECT_TIMEOUT_MS,
	// Storage type
	STORAGE_TYPE: 'local',
};
