import { env } from '@/env';

export const authConfig = {
	ACCESS_TOKEN_SECRET: env.ACCESS_TOKEN_SECRET,
	ACCESS_TOKEN_EXPIRES_IN: env.ACCESS_TOKEN_EXPIRES_IN,
	REFRESH_TOKEN_SECRET: env.REFRESH_TOKEN_SECRET,
	REFRESH_TOKEN_EXPIRES_IN: env.REFRESH_TOKEN_EXPIRES_IN
};
