#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "\nRunning Prettier to format staged files..."
npm run format:staged --silent

echo "\nRunning ESLint to lint staged files..."
npm run lint:staged --silent
