name: e2e testing flow 

on:
  push:
    branches:
      - 'releases/**'
      - 'master'
      - 'develop'
  pull_request:
    branches:
      - 'releases/**'
      - 'master'
      - 'develop'

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 20.x ]
        mongodb-version: [ '6.0' ]

    steps:
    - name: Git checkout
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.10.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}
        mongodb-username: ${{ secrets.MONGO_USERNAME }}
        mongodb-password:  ${{ secrets.MONGO_PASSWORD }}
        mongodb-db: ${{ secrets.MONGO_DATABASE }}

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm run test:e2e
      env:
        LOGGER_ENABLED: false
        MONGO_USERNAME: ${{ secrets.MONGO_USERNAME }}
        MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
        MONGO_DATABASE: ${{ secrets.MONGO_DATABASE }}
        MONGO_HOST: 'localhost'
        MONGO_PARAMS: 'authMechanism=DEFAULT&authSource=admin'