name: Unit Testing Flow 

on:
  push:
    branches:
      - 'releases/**'
      - 'master' 
  pull_request:

jobs:
  run-tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Execute Unit tests
        run: |
          npm ci
          npm run test