name: unit testing flow

on:
    push:
        branches:
            - 'releases/**'
            - 'master'
            - 'develop'
    pull_request:

jobs:
    run-tests:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [20.x]

        steps:
            - name: Git checkout
              uses: actions/checkout@v3

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install dependencies
              run: npm ci

            - name: Run tests
              run: npm run test
