name: Unit Testing Flow 

on:
  push:
    branches:
      - 'releases/**'
      - 'master' 
  pull_request:

jobs:
  run-tests:
    name: App Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout under $GITHUB_WORKSPACE
        uses: actions/checkout@main

      - name: Set up NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 18
      
      - name: Install all dependencies
        run: npm install
      
      - name: Run tests
        run: npm run test
